### ISSUE TITLE
Error while running gitstats with linux kernel repository and old git versions

### ISSUE THREAD

**Issue by athanrous** [hoxu/gitstats#20]
Original title: Error while running gitstats with opensuse kernel

I've cloned the following repository 

git://gitorious.org/opensuse/kernel.git 

While running ./gitstats /path/to/git/repo /output/folder I face this error

"[2.11899] >> git shortlog -s "v3.0.78" "^v3.9.1"
[1.76242] >> git shortlog -s "v3.4.45" "^v3.0.78"
[1.95104] >> git shortlog -s "v3.8.13" "^v3.4.45"
[0.57330] >> git shortlog -s "v3.9.2" "^v3.8.13"
[0.69536] >> git shortlog -s "v3.10-rc1" "^v3.9.2"
[1.95851] >> git shortlog -s "v3.2.45" "^v3.10-rc1"
[6.77937] >> git shortlog -s "rpm-3.0.74-0.6.8" "^v3.2.45"
[0.03402] >> git shortlog -s "v3.0.79" "^rpm-3.0.74-0.6.8"
[1.77202] >> git shortlog -s "v3.4.46" "^v3.0.79"
[2.23483] >> git shortlog -s "v3.9.3" "^v3.4.46"
[0.71021] >> git shortlog -s "v3.10-rc2" "^v3.9.3"
[12.44785] >> git rev-list --pretty=format:"%at %ai %aN <%aE>" HEAD | grep -v ^commit
Traceback (most recent call last):
  File "./gitstats", line 1430, in <module>
    g.run(sys.argv[1:])
  File "./gitstats", line 1407, in run
    data.collect(gitpath)
  File "./gitstats", line 312, in collect
    author, mail = parts[4].split('<', 1)
IndexError: list index out of range
"
FYI 
a) I repeated the process more than 3 times and the error still appears.
b) With other repositories I had no issue or any error while running ./gitstats.

**Comment by amadio** [comment]
We have hit this problem in Gentoo as well. The error can be reproduced by running gitstats on https://github.com/gentoo-science/sci. The corresponding Gentoo bug is here: https://bugs.gentoo.org/show_bug.cgi?id=575946

The problem is that git rev-list has invalid UTF-8 characters from authors' names.

I will create a pull request with a possible solution to this problem for @hoxu's review.
