### ISSUE TITLE
shutil.Error: gitstats.css and gitstats.css are the same file

### ISSUE THREAD

**Issue by sammcj** [hoxu/gitstats#46]
```
Refining data...
Saving cache...
Generating report...
Traceback (most recent call last):
  File "./gitstats", line 1490, in <module>
    g.run(sys.argv[1:])
  File "./gitstats", line 1477, in run
    report.create(data, outputpath)
  File "./gitstats", line 744, in create
    shutil.copyfile(src, path + '/' + file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `/Users/samm/othergit/gitstats/gitstats.css` and `/Users/samm/othergit/gitstats/gitstats.css` are the same file
```

**Comment by hoxu** [comment]
And what are the parameters? Seems likely you are trying to use the gitstats clone as both the source and output directory.
