### ISSUE TITLE
IndexError: list index out of range during collect

### ISSUE THREAD

**Issue by coreyt** [hoxu/gitstats#49]
When running gitstats, I am seeing an IndexError: list index out of range error.  This is the first time running gitstats on this repo. 
```
[[0.08800] >> git cat-file blob 42468d8ff605ff955b875916bfc80acdf95fe1c4 | wc -l
2.71800] >> git cat-file blob b2c62966c30359a015256e3f513bac08331438c0 | wc -l
Traceback (most recent call last):
  File "gitstats.py", line 1490, in <module>
    g.run(sys.argv[1:])
  File "gitstats.py", line 1465, in run
    data.collect(gitpath)
  File "gitstats.py", line 518, in collect
    ext_blob_linecount = pool.map(getnumoflinesinblob, blobs_to_read)
  File "C:\Python27\Lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\Lib\multiprocessing\pool.py", line 558, in get
    raise self._value
IndexError: list index out of range
```

When I run this `git cat-file` command, this is what is returned:
```
C:\projects\sandbox>git cat-file blob d469d018cece658a71ced1c7cf3cfffce2d24f9d | wc -l
     97

C:\projects\sandbox>git cat-file blob 61f9e75f9b63ded44c5d3fc9a9269bb86bb647bd | wc -l
    161

C:\projects\sandbox>git cat-file blob 88e064f90313a614abd6b3a2081bcb21c0539cb2 | wc -l
     45

C:\projects\sandbox>git cat-file blob 7180af8494c4dae57cad082b42277298b00b8669 | wc -l
    331

C:\projects\sandbox>git cat-file blob 49ffd7368bc396cd10dbf3e7439b7d0f296010cf | wc -l
     97

C:\projects\sandbox>git cat-file blob f0ce1e6845fff2a765cad458e987fc06f083b3f7 | wc -l
    250

C:\projects\sandbox>git cat-file blob df0fc164e6b33bbc382d5a6c51c002199b551834 | wc -l
     26

C:\projects\sandbox>git cat-file blob a6912c1194cc19ce52e58ca03de5ded92835eb7b | wc -l
     32

C:\projects\sandbox>git cat-file blob 42468d8ff605ff955b875916bfc80acdf95fe1c4 | wc -l
    109

C:\projects\sandbox>git cat-file blob b2c62966c30359a015256e3f513bac08331438c0 | wc -l
     96

C:\projects\sandbox>git cat-file blob d7ac3f820842c8eed99882cdba9b89d729070415 | wc -l
    107

C:\projects\sandbox>git cat-file blob 9f3794ba017d460ad9ef77004f95755bc4817ffb | wc -l
     76

C:\projects\sandbox>git cat-file blob f558f59e09d9e181a6a35a08092ed46ed3380916 | wc -l
    236

C:\projects\sandbox>git cat-file blob f5f7834784f05eb7291cf54152b84996dcbe7b7b | wc -l
     11

C:\projects\sandbox>git cat-file blob 69eaececede172cf1029c7c0c1d7adef505b924d | wc -l
     89
```

**Comment by corey-thompson** [comment]
All, I set processes to 1 on the command line and re-ran it.  It worked.  Reason I did this is because of other threads on the internet stating that Windows & Python with multiprocessing module is a bit wonky, and first try to fix issues with it is to reduce multiple processes to equal to or less than the number of physical processors on the machine.
